function info = import_measures(filename, dataLines)
%IMPORTFILE Import data from a text file
%  INFO = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  INFO = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  info = importfile("C:\Users\federico\MATLAB\Projects\mandown_plots\info.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Mar-2024 10:51:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["pre_process_speed", "inference_speed", "post_process_speed", "man_down_speed", "deep_sort_speed", "CPU_utilization_rate", "CPU_temperature", "CPU_power_consumption", "GPU_memory_used", "GPU_utilization_rate", "GPU_temperature", "GPU_power_consumption"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
info = readtable(filename, opts);

end